config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:create]
  resources :board_games
  resources :images
  resources :wished_games, except: [:create, :destroy]
  resources :owned_games, except: [:create, :destroy]
  resources :addresses
  devise_for :users

  # Custom trades routes
  post '/trades/', to: 'trades#create', as: 'create_trade'

  # Custom wished_games routes
  post '/wished_games/:id', to: 'wished_games#create', as: 'create_wished_game'
  delete '/wished_games/:id', to: 'wished_games#destroy', as: 'destroy_wished_game'

  # Custom owned_games routes
  post '/owned_games/:id', to: 'owned_games#create', as: 'create_owned_game'
  delete '/owned_games/:id', to: 'owned_games#destroy', as: 'destroy_owned_game'

  root to: "board_games#index"
end

app/views/shared/_navbar.html.erb
<nav>
    <% if user_signed_in? %>
      <span class="usernameButton"> <%= "Logged in as: #{current_user.email}" %> </span>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>    
</nav>

app/views/shared/_primary-navbar.html.erb
<nav class="primary-nav">
    <%= link_to "Top Games", root_path %>
    <%= link_to "Collection", owned_games_path %>
    <%= link_to "Trades", trades_path %>
    <%= link_to "Wishlist", wished_games_path %> 
</nav>

app/views/shared/_secondary-navbar.html.erb
<nav class="secondary-nav">
    <% if user_signed_in? %>
      <%= image_tag current_user.picture if current_user.picture.attached? %>
      <span class="usernameButton"> <%= "Logged in as: #{current_user.email}" %> </span>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>    
</nav>