config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:create]
  resources :board_games
  resources :images
  resources :wished_games, except: [:create, :destroy]
  resources :owned_games, except: [:create, :destroy]
  resources :addresses
  devise_for :users

  # Custom trades routes
  post '/trades/', to: 'trades#create', as: 'create_trade'

  # Custom wished_games routes
  post '/wished_games/:id', to: 'wished_games#create', as: 'create_wished_game'
  delete '/wished_games/:id', to: 'wished_games#destroy', as: 'destroy_wished_game'

  # Custom owned_games routes
  post '/owned_games/:id', to: 'owned_games#create', as: 'create_owned_game'
  delete '/owned_games/:id', to: 'owned_games#destroy', as: 'destroy_owned_game'

  root to: "board_games#index"
end

app/models/board_game.rb
class BoardGame < ApplicationRecord
    has_many :owned_games
    has_many :wished_games

    has_many :requestor_trades, class_name: 'Trade', foreign_key: :requestor_board_game_id
    has_many :requestee_trades, class_name: 'Trade', foreign_key: :requestee_board_game_id

    scope :ordered_by_rank, -> { order(overall_rank: :asc) }
end

app/controllers/board_games_controller.rb
class BoardGamesController < ApplicationController
  before_action :set_board_game, only: [:show, :edit, :update, :destroy]

  # GET /board_games
  # GET /board_games.json
  def index
    # Using the .ordered_by_rank scope (found on the board_game model), SQL search is automatically contained in a single query
    @board_games = BoardGame.all.ordered_by_rank
  end

  # GET /board_games/1
  # GET /board_games/1.json
  def show
  end

  # GET /board_games/new
  def new
    @board_game = BoardGame.new
  end

  # GET /board_games/1/edit
  def edit
  end

  # POST /board_games
  # POST /board_games.json
  def create
    @board_game = BoardGame.new(board_game_params)

    respond_to do |format|
      if @board_game.save
        format.html { redirect_to @board_game, notice: 'Board game was successfully created.' }
        format.json { render :show, status: :created, location: @board_game }
      else
        format.html { render :new }
        format.json { render json: @board_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_games/1
  # PATCH/PUT /board_games/1.json
  def update
    respond_to do |format|
      if @board_game.update(board_game_params)
        format.html { redirect_to @board_game, notice: 'Board game was successfully updated.' }
        format.json { render :show, status: :ok, location: @board_game }
      else
        format.html { render :edit }
        format.json { render json: @board_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_games/1
  # DELETE /board_games/1.json
  def destroy
    @board_game.destroy
    respond_to do |format|
      format.html { redirect_to board_games_url, notice: 'Board game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_game
      @board_game = BoardGame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_game_params
      params.fetch(:board_game, {})
    end
end

app/helpers/board_games_helper.rb
module BoardGamesHelper
end

app/views/board_games/_bg_tile.html.erb
<div class='tiles-container'>
    <% @board_games.each do |board_game| %>
        <div class='board-game-tile'>
            <%= link_to image_tag(board_game.image, class: "card-image", alt: "#{board_game.name} Front Cover"), board_game %>
            <div class='board-game-stats'>
                <div class='board-game-name'>
                    <h2><%= "#{board_game.name} (#{board_game.year_published})" %></h2>
                </div>
                <div class='board-game-rank-buttons-container'>
                    <div class='board-game-rank-rating'>
                        <%= "#{board_game.overall_rank}" %>
                        <h3>Rank</h3>
                        <%= "#{board_game.geek_rating}" %>
                        <h3>Rating</h3>
                    </div>
                    <div class='board-game-buttons'>
                        <%= button_to 'Add to Wishlist', create_wished_game_path(board_game), method: :post %>
                        <%= button_to 'Add to Collection', create_owned_game_path(board_game), method: :post %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/board_games/_form.html.erb
<%= form_with(model: board_game, local: true) do |form| %>
  <% if board_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_game.errors.count, "error") %> prohibited this board_game from being saved:</h2>

      <ul>
        <% board_game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_games/edit.html.erb
<h1>Editing Board Game</h1>

<%= render 'form', board_game: @board_game %>

<%= link_to 'Show', @board_game %> |
<%= link_to 'Back', board_games_path %>

app/views/board_games/index.html.erb
<%= render 'bg_tile' %>

app/views/board_games/new.html.erb
<h1>New Board Game</h1>

<%= render 'form', board_game: @board_game %>

<%= link_to 'Back', board_games_path %>

app/views/board_games/show.html.erb
<div class='board-game-page'>
    <div class='board-game-rank-rating'>
        <p><%= "#{@board_game.overall_rank}" %></p>
        <h3>Rank</h3>
        <p><%= "#{@board_game.geek_rating}" %></p>
        <h3>Rating</h3>
    </div>
    <div class='board-game-info'>
        <div class='board-game-show-name'>
            <h1><%= "#{@board_game.name} (#{@board_game.year_published})" %></h1>
        </div>
        <div class='board-game-play-stats'>
            <p><%= "Players: #{@board_game.min_players} - #{@board_game.max_players}" %></p>
            <p><%= "Age: #{@board_game.age}+" %></p>
            <p><%= "Playing Time: #{@board_game.min_playing_time} - #{@board_game.max_playing_time}" %></p>
            <p><%= "Weight: #{@board_game.weight}/5" %></p>
            <p><%= button_to 'Add to Wishlist', create_wished_game_path(@board_game), method: :post %></p>
            <p><%= button_to 'Add to Collection', create_owned_game_path(@board_game), method: :post %></p>
        </div>
    </div>
    <div class='board-game-image-container'>
        <%= image_tag(@board_game.image, class: "board-game-image", alt: "#{@board_game.name} Front Cover") %>
    </div>
    <div class='board-game-description'>
        <p><%= @board_game.long_description %></p>
    </div>
</div>